version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: deploy/install_dependencies.sh
      timeout: 1000
      runas: root
  Install:
    - location: deploy/install.sh
      timeout: 1000
      runas: root
  ApplicationStart:
    # Inicia la aplicación com ubuntu
    - location: deploy/start.sh
      timeout: 1000
      runas: root
  ApplicationStop:
  # Para la aplicación
    - location: deploy/stop.sh
      timeout: 1000
      runas: root